expense_tracker/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("users/", include("users.urls")),
    path("expenses/", include("expenses.urls")),
    path("budgeting/", include("budgeting.urls")),
    path("investments/", include("investment_tracker.urls")),
    path("debts/", include("debt_tracker.urls")),
    path("income/", include("income.urls")),
    path("settings/", include("settings.urls")),
    path("", include("expenses.urls")),
]

investment_tracker/urls.py
from django.urls import path

from .views import (
    InvestmentCreateView,
    InvestmentDeleteView,
    InvestmentListView,
    InvestmentTypeCreateView,
    InvestmentTypeDeleteView,
    InvestmentTypeListView,
    InvestmentTypeUpdateView,
    InvestmentUpdateView,
    PlatformCreateView,
    PlatformDeleteView,
    PlatformListView,
    PlatformUpdateView,
)

app_name = "investment_tracker"

urlpatterns = [
    path("", InvestmentListView.as_view(), name="investment_list"),
    path("create/", InvestmentCreateView.as_view(), name="investment_create"),
    path("<int:pk>/update/", InvestmentUpdateView.as_view(), name="investment_update"),
    path("<int:pk>/delete/", InvestmentDeleteView.as_view(), name="investment_delete"),
    path("platforms/", PlatformListView.as_view(), name="platform_list"),
    path("platforms/create/", PlatformCreateView.as_view(), name="platform_create"),
    path(
        "platforms/<int:pk>/update/",
        PlatformUpdateView.as_view(),
        name="platform_update",
    ),
    path(
        "platforms/<int:pk>/delete/",
        PlatformDeleteView.as_view(),
        name="platform_delete",
    ),
    path("types/", InvestmentTypeListView.as_view(), name="investmenttype_list"),
    path(
        "types/create/",
        InvestmentTypeCreateView.as_view(),
        name="investmenttype_create",
    ),
    path(
        "types/<int:pk>/update/",
        InvestmentTypeUpdateView.as_view(),
        name="investmenttype_update",
    ),
    path(
        "types/<int:pk>/delete/",
        InvestmentTypeDeleteView.as_view(),
        name="investmenttype_delete",
    ),
]

users/urls.py
from django.urls import path

from . import views

app_name = "users"

urlpatterns = [
    path("register/", views.register, name="register"),
    path("login/", views.UserLoginView.as_view(), name="login"),
    path("logout/", views.UserLogoutView.as_view(), name="logout"),
]

investment_tracker/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone

from expenses.models import PaymentMethod


class Platform(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    class Meta:
        unique_together = ("user", "name")

    def __str__(self):
        return self.name


class InvestmentType(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=100)

    class Meta:
        unique_together = ("user", "name")

    def __str__(self):
        return self.name


class Investment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date = models.DateTimeField(default=timezone.now)
    investment_type = models.ForeignKey(InvestmentType, on_delete=models.CASCADE)
    platform = models.ForeignKey(Platform, on_delete=models.CASCADE)
    amount = models.DecimalField(max_digits=10, decimal_places=2)
    description = models.TextField()
    payment_method = models.ForeignKey(
        PaymentMethod, on_delete=models.SET_NULL, null=True, blank=True
    )

    def __str__(self):
        return f"{self.date.strftime('%Y-%m-%d')} - {self.investment_type.name} - {self.amount}"

investment_tracker/forms.py
from django import forms

from expenses.models import PaymentMethod

from .models import Investment, InvestmentType, Platform


class PlatformForm(forms.ModelForm):
    class Meta:
        model = Platform
        fields = ["name"]
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control"}),
        }


class InvestmentTypeForm(forms.ModelForm):
    class Meta:
        model = InvestmentType
        fields = ["name"]
        widgets = {
            "name": forms.TextInput(attrs={"class": "form-control"}),
        }


class InvestmentForm(forms.ModelForm):
    class Meta:
        model = Investment
        fields = [
            "date",
            "investment_type",
            "platform",
            "amount",
            "description",
            "payment_method",
        ]
        widgets = {
            "date": forms.DateTimeInput(
                attrs={"type": "datetime-local", "class": "form-control"}
            ),
            "investment_type": forms.Select(attrs={"class": "form-select"}),
            "platform": forms.Select(attrs={"class": "form-select"}),
            "payment_method": forms.Select(attrs={"class": "form-select"}),
            "amount": forms.NumberInput(attrs={"class": "form-control"}),
            "description": forms.Textarea(attrs={"class": "form-control", "rows": 3}),
        }

    def __init__(self, *args, **kwargs):
        user = kwargs.pop("user", None)
        super(InvestmentForm, self).__init__(*args, **kwargs)
        if user:
            self.fields["investment_type"].queryset = InvestmentType.objects.filter(
                user=user
            )
            self.fields["platform"].queryset = Platform.objects.filter(user=user)
            self.fields["payment_method"].queryset = PaymentMethod.objects.filter(
                user=user
            )
        self.fields["investment_type"].empty_label = "Select an investment type"
        self.fields["platform"].empty_label = "Select a platform"
        self.fields["payment_method"].empty_label = "Select a payment method"

investment_tracker/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from .forms import InvestmentForm, InvestmentTypeForm, PlatformForm
from .models import Investment, InvestmentType, Platform


class InvestmentListView(LoginRequiredMixin, ListView):
    model = Investment
    template_name = "investment_tracker/investment_list.html"
    context_object_name = "investments"

    def get_queryset(self):
        return Investment.objects.filter(user=self.request.user)


class InvestmentCreateView(LoginRequiredMixin, CreateView):
    model = Investment
    form_class = InvestmentForm
    template_name = "investment_tracker/investment_form.html"
    success_url = reverse_lazy("investment_tracker:investment_list")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class InvestmentUpdateView(LoginRequiredMixin, UpdateView):
    model = Investment
    form_class = InvestmentForm
    template_name = "investment_tracker/investment_form.html"
    success_url = reverse_lazy("investment_tracker:investment_list")

    def get_form_kwargs(self):
        kwargs = super().get_form_kwargs()
        kwargs["user"] = self.request.user
        return kwargs


class InvestmentDeleteView(LoginRequiredMixin, DeleteView):
    model = Investment
    template_name = "investment_tracker/investment_confirm_delete.html"
    success_url = reverse_lazy("investment_tracker:investment_list")


class PlatformListView(LoginRequiredMixin, ListView):
    model = Platform
    template_name = "investment_tracker/platform_list.html"
    context_object_name = "platforms"

    def get_queryset(self):
        return Platform.objects.filter(user=self.request.user)


class PlatformCreateView(LoginRequiredMixin, CreateView):
    model = Platform
    form_class = PlatformForm
    template_name = "investment_tracker/platform_form.html"
    success_url = reverse_lazy("investment_tracker:platform_list")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class PlatformUpdateView(LoginRequiredMixin, UpdateView):
    model = Platform
    form_class = PlatformForm
    template_name = "investment_tracker/platform_form.html"
    success_url = reverse_lazy("investment_tracker:platform_list")


class PlatformDeleteView(LoginRequiredMixin, DeleteView):
    model = Platform
    template_name = "investment_tracker/platform_confirm_delete.html"
    success_url = reverse_lazy("investment_tracker:platform_list")


class InvestmentTypeListView(LoginRequiredMixin, ListView):
    model = InvestmentType
    template_name = "investment_tracker/investmenttype_list.html"
    context_object_name = "investment_types"

    def get_queryset(self):
        return InvestmentType.objects.filter(user=self.request.user)


class InvestmentTypeCreateView(LoginRequiredMixin, CreateView):
    model = InvestmentType
    form_class = InvestmentTypeForm
    template_name = "investment_tracker/investmenttype_form.html"
    success_url = reverse_lazy("investment_tracker:investmenttype_list")

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)


class InvestmentTypeUpdateView(LoginRequiredMixin, UpdateView):
    model = InvestmentType
    form_class = InvestmentTypeForm
    template_name = "investment_tracker/investmenttype_form.html"
    success_url = reverse_lazy("investment_tracker:investmenttype_list")


class InvestmentTypeDeleteView(LoginRequiredMixin, DeleteView):
    model = InvestmentType
    template_name = "investment_tracker/investmenttype_confirm_delete.html"
    success_url = reverse_lazy("investment_tracker:investmenttype_list")

templates/investment_tracker/investment_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Confirm Delete{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>Are you sure you want to delete this investment?</h2>
    <p>{{ investment.investment_type.name }} on {{ investment.platform.name }}</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
        <a href="{% url 'investment_tracker:investment_list' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

templates/investment_tracker/investment_form.html
{% extends 'base.html' %}

{% block title %}{% if form.instance.pk %}Edit Investment{% else %}Create Investment{% endif %}{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>{% if form.instance.pk %}Edit Investment{% else %}Create Investment{% endif %}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}

templates/investment_tracker/investment_list.html
{% extends 'base.html' %}

{% block title %}Investments{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h2 class="mb-0">Investments</h2>
        <a href="{% url 'investment_tracker:investment_create' %}" class="btn btn-primary">Add New Investment</a>
    </div>
    <div class="list-group">
        {% for investment in investments %}
        <div class="list-group-item">
            <div class="d-flex w-100 justify-content-between">
                <h5 class="mb-1">{{ investment.investment_type.name }} on {{ investment.platform.name }}</h5>
                <small>{{ investment.date|date:"Y-m-d" }}</small>
            </div>
            <p class="mb-1">Amount: ${{ investment.amount }}</p>
            {% if investment.payment_method %}
            <p class="mb-1">Payment Method: {{ investment.payment_method.name }}</p>
            {% endif %}
            <p class="mb-1">Description: {{ investment.description }}</p>
            <div>
                <a href="{% url 'investment_tracker:investment_update' investment.pk %}"
                    class="btn btn-sm btn-info">Edit</a>
                <a href="{% url 'investment_tracker:investment_delete' investment.pk %}"
                    class="btn btn-sm btn-danger">Delete</a>
            </div>
        </div>
        {% empty %}
        <p class="list-group-item">No investments found.</p>
        {% endfor %}
    </div>
</div>
{% endblock %}

templates/investment_tracker/investmenttype_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Confirm Delete{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>Are you sure you want to delete this investment type?</h2>
    <p>{{ investmenttype.name }}</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
        <a href="{% url 'investment_tracker:investmenttype_list' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

templates/investment_tracker/investmenttype_form.html
{% extends 'base.html' %}

{% block title %}{% if form.instance.pk %}Edit Investment Type{% else %}Create Investment Type{% endif %}{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>{% if form.instance.pk %}Edit Investment Type{% else %}Create Investment Type{% endif %}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}

templates/investment_tracker/investmenttype_list.html
{% extends 'base.html' %}

{% block title %}Investment Types{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h2>Investment Types</h2>
        <a href="{% url 'investment_tracker:investmenttype_create' %}" class="btn btn-primary">Add New Investment
            Type</a>
    </div>
    <ul class="list-group">
        {% for type in investment_types %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
            {{ type.name }}
            <div>
                <a href="{% url 'investment_tracker:investmenttype_update' type.pk %}"
                    class="btn btn-sm btn-info">Edit</a>
                <a href="{% url 'investment_tracker:investmenttype_delete' type.pk %}"
                    class="btn btn-sm btn-danger">Delete</a>
            </div>
        </li>
        {% empty %}
        <li class="list-group-item">No investment types found.</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}

templates/investment_tracker/platform_confirm_delete.html
{% extends 'base.html' %}

{% block title %}Confirm Delete{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>Are you sure you want to delete this platform?</h2>
    <p>{{ platform.name }}</p>
    <form method="post">
        {% csrf_token %}
        <button type="submit" class="btn btn-danger">Delete</button>
        <a href="{% url 'investment_tracker:platform_list' %}" class="btn btn-secondary">Cancel</a>
    </form>
</div>
{% endblock %}

templates/investment_tracker/platform_form.html
{% extends 'base.html' %}

{% block title %}{% if form.instance.pk %}Edit Platform{% else %}Create Platform{% endif %}{% endblock %}

{% block content %}
<div class="container mt-4">
    <h2>{% if form.instance.pk %}Edit Platform{% else %}Create Platform{% endif %}</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">Save</button>
    </form>
</div>
{% endblock %}

templates/investment_tracker/platform_list.html
{% extends 'base.html' %}

{% block title %}Platforms{% endblock %}

{% block content %}
<div class="container mt-4">
    <div class="d-flex justify-content-between align-items-center mb-3">
        <h2>Platforms</h2>
        <a href="{% url 'investment_tracker:platform_create' %}" class="btn btn-primary">Add New Platform</a>
    </div>
    <ul class="list-group">
        {% for platform in platforms %}
        <li class="list-group-item d-flex justify-content-between align-items-center">
            {{ platform.name }}
            <div>
                <a href="{% url 'investment_tracker:platform_update' platform.pk %}"
                    class="btn btn-sm btn-info">Edit</a>
                <a href="{% url 'investment_tracker:platform_delete' platform.pk %}"
                    class="btn btn-sm btn-danger">Delete</a>
            </div>
        </li>
        {% empty %}
        <li class="list-group-item">No platforms found.</li>
        {% endfor %}
    </ul>
</div>
{% endblock %}